### ISSUE TITLE
Missing data in headers when using quickssrf preview

### ISSUE THREAD

**Issue by RahulVivekNair** [bebiksior/EvenBetter#39]
I noticed that some headers when not in the expected format like User-agent, some of the information gets clipped.
![image](https://github.com/bebiksior/EvenBetter/assets/68507071/c46ad897-e75c-4776-b436-3bcff0688fb9)
The issue seems to be that the user agent returns with a ':' which probably breaks the formatting.
Here's how it's supposed to look like.
![image](https://github.com/bebiksior/EvenBetter/assets/68507071/4cc4be7f-d9a5-4a63-ab2f-b5bc7432068d)

Imo, the preview should accurately reflect exactly how the request was received ,incase there are some weird formats returned while testing out of band vulns.

**Comment by bebiksior** [comment]
Thanks for reporting this issue! Will fix it in the next release :D
